currLabel: Einträge
customIcon: null
enabled: 1
handle: entries
icon: section
layout: 1e06c5fa-d04f-4336-afaf-b5c8f8f1094d # Default
level: 1
newWindow: 0
parentId: null
prevLabel: Einträge
prevLevel: null
prevParentId: null
prevUrl: entries
sortOrder: 1
type: craft
url: entries
