altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2ae2f316-5b3b-4e0b-abba-17d5b7ab0a97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T16:10:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 74d62d49-9aa9-4ffa-8b60-67f2e64d33af
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: c604598d-6afa-4daf-b274-5a9b6d31a785
        userCondition: null
fs: personen
handle: personen
name: Personen
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
