dateModified: 1554136753
email:
  fromEmail: p@henrik-hentschel.de
  fromName: 'Andrea Film'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  b6201258-940b-4113-ba3b-d6e2b2aa38e1:
    name: Common
  7dd38e4e-2004-4c25-9623-4a50770124d8:
    name: Drinks
  05290696-2d33-4040-8bdf-ecb9e2593586:
    name: General
  57800bf4-49d4-4aa9-ac2b-9953569db0ef:
    name: News
  695f2705-9ba1-4d94-800b-7601fa8fd1f0:
    name: About
  9256a3ac-dd6e-4b9a-bb95-5ed9b5249701:
    name: Films
  983dcdf8-d626-4aed-b9ef-7a181b0c1bbc:
    name: Homepage
fields:
  d655e5be-d31c-48a7-8587-ff8423fa00d0:
    name: 'Drinks Intro'
    handle: drinksIntro
    instructions: 'A short Introduction'
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 7dd38e4e-2004-4c25-9623-4a50770124d8
  69983b47-acee-48fe-a414-30b622fe223b:
    name: Inhaltsfeld
    handle: contentField
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      cleanupHtml: '1'
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
    contentColumnType: text
    fieldGroup: 05290696-2d33-4040-8bdf-ecb9e2593586
  04a8398f-e475-4c20-8b5e-ff34d79210de:
    name: 'News Excerpt'
    handle: newsExcerpt
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 57800bf4-49d4-4aa9-ac2b-9953569db0ef
  54f6e39b-7a48-4853-aa96-ae218d4bacad:
    name: 'News Body'
    handle: newsBody
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      cleanupHtml: '1'
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
    contentColumnType: text
    fieldGroup: 57800bf4-49d4-4aa9-ac2b-9953569db0ef
  554e73b2-36b3-4fe6-a4bc-6628e7941e76:
    name: 'Drink Image'
    handle: drinkImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: 'Chosse a Drink Image'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 7dd38e4e-2004-4c25-9623-4a50770124d8
  5eec0c3a-943f-4959-b56a-bdb2c1ddc2f6:
    name: Subtitel
    handle: subtitle
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 695f2705-9ba1-4d94-800b-7601fa8fd1f0
  f8035747-f395-413b-81cb-077ad48d657a:
    name: 'Page Intro'
    handle: pageIntro
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 695f2705-9ba1-4d94-800b-7601fa8fd1f0
  95b6bd76-0ca5-46fe-b075-9cb9e9663005:
    name: Video
    handle: videoID
    instructions: 'Nummer vimeo.com/327554892'
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: '327554892'
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
  f7647892-8b56-4f2c-bf36-036bfff0df4b:
    name: 'Film Image'
    handle: filmImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: ''
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
  8837aea0-a136-4261-8bd5-5272b7e8172d:
    name: Jahreszahl
    handle: yearFilm
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
  002dc819-24d2-428e-9e9c-d279dd8f112f:
    name: Creditbox
    handle: creditbox
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_creditbox}}'
      localizeBlocks: false
    contentColumnType: string
    fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
  269746c8-f044-4f33-a3e7-f6a27dea14ae:
    name: Video
    handle: videoFileHome
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - video
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: ''
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 983dcdf8-d626-4aed-b9ef-7a181b0c1bbc
  4a983616-a6d6-44b4-9cc0-f7118261de07:
    name: 'Video Standbild'
    handle: videoStillImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:9161c7ba-81a8-43c7-88a0-1c31bc63965e'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: ''
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 983dcdf8-d626-4aed-b9ef-7a181b0c1bbc
imageTransforms:
  db1f962f-5da7-4a16-a238-a313824e5c72:
    format: null
    handle: filmThumbImg
    height: '400'
    interlace: none
    mode: crop
    name: '600x400 FilmThumb'
    position: center-center
    quality: null
    width: '600'
  3262e568-8b53-4657-9be4-b54fe9e0b1d7:
    format: null
    handle: fullImage
    height: ''
    interlace: none
    mode: crop
    name: 'Full IMage'
    position: center-center
    quality: null
    width: '1920'
matrixBlockTypes:
  10ba63eb-689c-4558-8c91-7e6b4f45a460:
    field: 002dc819-24d2-428e-9e9c-d279dd8f112f
    name: Creditline
    handle: creditline
    sortOrder: 1
    fields:
      1c4795f4-32d4-4671-8316-84b8c342311f:
        name: 'Credit Label'
        handle: creditLabel
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: Label
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
      42c4a58f-7215-463d-ba64-6c346ab02572:
        name: 'Credit Text'
        handle: creditText
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: '1'
          initialRows: '3'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      5eb00478-8bed-49c4-8126-6412f53eb707:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              1c4795f4-32d4-4671-8316-84b8c342311f:
                required: false
                sortOrder: 1
              42c4a58f-7215-463d-ba64-6c346ab02572:
                required: false
                sortOrder: 2
plugins:
  ckeditor:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.2.2
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
sections:
  381f95a2-5ab7-4b9d-9a8b-ae3c3a5efbbf:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: false
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index.twig
    entryTypes:
      ec7692f4-f47a-4290-b6bd-3803680586f6:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          0838e0c3-1e02-47dc-af5b-e6d7cd820336:
            tabs:
              -
                name: Homepage
                sortOrder: 1
                fields:
                  269746c8-f044-4f33-a3e7-f6a27dea14ae:
                    required: false
                    sortOrder: 1
                  4a983616-a6d6-44b4-9cc0-f7118261de07:
                    required: false
                    sortOrder: 2
  b063e1c5-e127-450e-8dd1-480f6deac923:
    name: About
    handle: aboutSection
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: about/
    structure:
      uid: c24e7b7b-1c27-4722-bf4f-4bc0b833d73f
      maxLevels: ''
    entryTypes:
      a4a96368-4fde-4bb3-85e9-f98695bbc66d:
        name: About
        handle: aboutSection
        hasTitleField: true
        titleLabel: 'Page Titel'
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          7f6f84ee-517f-4fe1-87ec-1b4d83068cc8:
            tabs:
              -
                name: About
                sortOrder: 1
                fields:
                  5eec0c3a-943f-4959-b56a-bdb2c1ddc2f6:
                    required: false
                    sortOrder: 1
                  f8035747-f395-413b-81cb-077ad48d657a:
                    required: false
                    sortOrder: 2
                  69983b47-acee-48fe-a414-30b622fe223b:
                    required: false
                    sortOrder: 3
  d925a667-69cb-457e-92eb-22c9f5975792:
    name: Drinks
    handle: drinksSection
    type: channel
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'drinks/{slug}'
        template: drinks/_entry
    entryTypes:
      0e61669f-fa8c-4da4-b70a-1951d90cf89f:
        name: Drinks
        handle: drinksSection
        hasTitleField: true
        titleLabel: Titel
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          ec711a4f-149d-4b3d-9915-3b7f9586f2d8:
            tabs:
              -
                name: Drinks
                sortOrder: 1
                fields:
                  554e73b2-36b3-4fe6-a4bc-6628e7941e76:
                    required: false
                    sortOrder: 1
                  d655e5be-d31c-48a7-8587-ff8423fa00d0:
                    required: false
                    sortOrder: 2
                  69983b47-acee-48fe-a414-30b622fe223b:
                    required: false
                    sortOrder: 3
  32e60c6a-8544-4297-9c0b-2894a3d4f370:
    name: Contact
    handle: contactSection
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: contact
        template: contact/_entry
    entryTypes:
      fd8bac83-e955-4b7d-b685-11622dbb13cf:
        name: Contact
        handle: contactSection
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  b544f202-05b6-4b0d-973d-17763a6a2d84:
    name: films
    handle: filmsSection
    type: channel
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{slug}'
        template: films/_entry
    entryTypes:
      1b4e3c8f-a2d4-4279-a90b-fee047511101:
        name: films
        handle: filmsSection
        hasTitleField: true
        titleLabel: Titel
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          a5adcbee-6aca-408c-958c-425e374e1e29:
            tabs:
              -
                name: 'Film Details'
                sortOrder: 1
                fields:
                  8837aea0-a136-4261-8bd5-5272b7e8172d:
                    required: false
                    sortOrder: 1
                  f7647892-8b56-4f2c-bf36-036bfff0df4b:
                    required: false
                    sortOrder: 2
                  69983b47-acee-48fe-a414-30b622fe223b:
                    required: false
                    sortOrder: 3
                  95b6bd76-0ca5-46fe-b075-9cb9e9663005:
                    required: false
                    sortOrder: 4
              -
                name: Credits
                sortOrder: 2
                fields:
                  002dc819-24d2-428e-9e9c-d279dd8f112f:
                    required: false
                    sortOrder: 1
  888462c5-883e-4fbc-b494-c46391f77a78:
    name: movies
    handle: moviesSection
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      eccd415c-2a08-4035-94cd-62a46c8cd0a2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: movies/_entry
    structure:
      uid: 9274c03e-7f90-48ab-af51-740abc5d74fb
      maxLevels: ''
    entryTypes:
      9cc9ec25-6ee0-4d3b-8c33-de5d753e77c8:
        name: movies
        handle: moviesSection
        hasTitleField: true
        titleLabel: Titel
        titleFormat: null
        sortOrder: 1
siteGroups:
  330548d1-b81b-4755-96d3-a57901c9800d:
    name: 'Andrea Film'
sites:
  eccd415c-2a08-4035-94cd-62a46c8cd0a2:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: de
    name: 'Andrea Film'
    primary: true
    siteGroup: 330548d1-b81b-4755-96d3-a57901c9800d
    sortOrder: 1
system:
  edition: solo
  name: 'Andrea Film'
  live: true
  schemaVersion: 3.1.25
  timeZone: Europe/Zurich
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  9161c7ba-81a8-43c7-88a0-1c31bc63965e:
    name: Drinks
    handle: drinks
    type: craft\volumes\Local
    hasUrls: true
    url: '@andreafilm_url/assets/images/drinks'
    settings:
      path: '@root/assets/images/drinks'
    sortOrder: '1'
  f7b6e1ba-4676-494b-bda5-666cf9d0533a:
    name: Films
    handle: films
    type: craft\volumes\Local
    hasUrls: true
    url: '@andreafilm_url/user_assets/images/films'
    settings:
      path: '@webroot/user_assets/images/films'
    sortOrder: '2'
