defaultPlacement: end
enableVersioning: true
entryTypes:
  - fd8bac83-e955-4b7d-b685-11622dbb13cf # Contact
handle: contactSection
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  eccd415c-2a08-4035-94cd-62a46c8cd0a2:
    enabledByDefault: true
    hasUrls: true
    template: contact/
    uriFormat: contact
type: single
