defaultPlacement: end
enableVersioning: true
entryTypes:
  - 12ede08a-8e47-43c2-b205-3b8fd714854f # Film
handle: filmsSection
maxAuthors: 1
name: Filme
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  eccd415c-2a08-4035-94cd-62a46c8cd0a2:
    enabledByDefault: true
    hasUrls: true
    template: films/_entry
    uriFormat: 'filme/{slug}'
structure:
  maxLevels: null
  uid: e293fa32-175d-4149-b22f-c505ac585cbd
type: structure
