enableVersioning: false
handle: homepage
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  eccd415c-2a08-4035-94cd-62a46c8cd0a2:
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
