contentColumnType: text
fieldGroup: 05290696-2d33-4040-8bdf-ecb9e2593586
handle: contentField
instructions: ''
name: Inhaltsfeld
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
