columnSuffix: null
contentColumnType: text
handle: contentField
instructions: null
name: Inhaltsfeld
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 9acf338d-de8b-41c4-a72f-07be62b25a2d # Formatierter Text
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
