columnSuffix: null
contentColumnType: text
fieldGroup: 4d7dbfa9-1442-453c-8342-8502890b71f4
handle: contactTextCH
instructions: null
name: 'Text Schweiz'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 9acf338d-de8b-41c4-a72f-07be62b25a2d # Formatierter Text
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
