contentColumnType: text
fieldGroup: 4d7dbfa9-1442-453c-8342-8502890b71f4
handle: contactTextCH
instructions: ''
name: 'Text Schweiz'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
