columnSuffix: null
contentColumnType: text
handle: contactTextFR
instructions: null
name: 'Text Frankreich'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: b84af26f-7dc4-4849-8a11-29881470d18c # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
