contentColumnType: string
handle: creditbox
instructions: ''
name: Creditbox
searchable: true
settings:
  entryTypes:
    - 10ba63eb-689c-4558-8c91-7e6b4f45a460
  localizeBlocks: false
  maxEntries: ''
  minEntries: ''
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
