columnSuffix: null
handle: creditLabel
instructions: null
name: 'Creditbox - Creditline - Credit Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Label
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
