contentColumnType: text
handle: filmSubtitle
instructions: ''
name: Subtitel
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '1'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
