contentColumnType: text
fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
handle: filmSubtitle
instructions: ''
name: Subtitel
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '1'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
