contentColumnType: text
fieldGroup: a5f5d17b-2754-4410-b70a-67b25b2c4b46
handle: filmDetailTitle
instructions: ''
name: 'Film Title'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
