columnSuffix: null
contentColumnType: string
handle: reviewsMatrix
instructions: null
name: Reviews
searchable: false
settings:
  entryTypes:
    - 8115fd63-b5c1-4708-8ba5-58ae7c3c450d
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
