contentColumnType: string
fieldGroup: 9256a3ac-dd6e-4b9a-bb95-5ed9b5249701
handle: videoBG
instructions: ''
name: 'Video Hintergrund'
searchable: true
settings:
  allowedKinds:
    - video
  defaultUploadLocationSource: 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a' # Films
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a' # Films
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:f7b6e1ba-4676-494b-bda5-666cf9d0533a' # Films
  targetSiteId: null
  useSingleFolder: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
