fieldLayouts:
  7f6f84ee-517f-4fe1-87ec-1b4d83068cc8:
    tabs:
      -
        elements:
          -
            instructions: null
            label: 'Page Titel'
            type: craft\fieldlayoutelements\entries\EntryTitleField
          -
            fieldUid: 5eec0c3a-943f-4959-b56a-bdb2c1ddc2f6 # Subtitel
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f8035747-f395-413b-81cb-077ad48d657a # Page Intro
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 69983b47-acee-48fe-a414-30b622fe223b # Inhaltsfeld
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f13b35b9-004c-4ccb-9b3c-073525339052 # Hintergrundbild
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4f0dec7a-50a1-4a37-9c5e-baec5cc417eb # Video Hintergrund
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: About
        sortOrder: 1
handle: aboutSection
hasTitleField: true
name: About
section: b063e1c5-e127-450e-8dd1-480f6deac923 # About
sortOrder: 1
titleFormat: ''
