color: null
fieldLayouts:
  5699f4fe-fda8-4df1-b0e3-e2ba8280490c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T16:03:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e233a01e-2332-406d-96c9-1936a061cc76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-30T16:10:48+00:00'
            elementCondition: null
            fieldUid: 315537d8-5143-4f75-bdfc-812e719318f1 # Bild Person
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c846e084-f877-4a08-8cf6-90a9ff649325
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d67563da-e1ea-44da-8ac1-d0d7e01b6f81
        userCondition: null
handle: person
hasTitleField: true
icon: ''
name: Person
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
